pipeline {
    agent {
        // 此处设定构建环境，目前可选有
        // default, java-8, python-3.5, ruby-2.3, go-1.11 等
        // 详情请阅 https://dev.tencent.com/help/knowledge-base/how-to-use-ci#agents
        label "default"
    }
    stages  {
        
        stage("检出") {
            steps {
                sh 'ci-init'
                checkout(
                  [$class: 'GitSCM', branches: [[name: env.GIT_BUILD_REF]], 
                  userRemoteConfigs: [[url: env.GIT_REPO_URL]]]
                )
            }
        }

        stage("构建") {
            steps {
                echo "构建中..."
                sh 'node -v'
                sh 'java -version'
               // sh 'mvn package' // mvn 示例
               sh 'mkdir ./target/'
               sh 'zip -r ./target/party-admin.zip ./party-admin '
               sh 'zip -r ./target/party-pcweb.zip ./party-pcweb '
               sh 'zip -r ./target/party-wechat.zip ./party-wechat ' 
             archiveArtifacts artifacts: '**/target/*.zip,**/target/*.jar', fingerprint: true //申明构造产物地址
                echo "构建完成."
            }
        }

     	stage("运行"){
      		steps {
                  echo "运行中..."
    	    }
    	}

        stage("部署") {
            steps {
                echo "部署中..."
                // 请在这里放置收集单元测试报告的调用过程，例如:
                // sh 'mvn tomcat7:deploy' // Maven tomcat7 插件示例：
                // sh './deploy.sh' // 自研部署脚本
                echo "部署完成"
            }
        }
    }
}